// LOCALHOST

### Get all posts
GET http://localhost:3000/posts

### Get a single post by ID
GET http://localhost:3000/posts/65c81c2049e45e4778590256

### Create a new post
POST http://localhost:3000/posts
content-type: application/json
    
{
  "title": "any",
  "author": "any",
  "topics": "any",
  "status": "any",
  "content": "any"
}

### Update a post
PUT http://localhost:3000/posts/65d05fe013930c39e1da0fa1
content-type: application/json
    
{
  //"title": "any",
  //"author": "any",
  //"topics": "any",
  //"status": "any",
  "content": "This post has been edited. That's cool!"
}

### Delete a post
DELETE http://localhost:3000/posts/65c97f13923abcac07b9094a


// PRODUCTION Deploy

### Get all posts
GET https://blog-api-service-ehy4.onrender.com/posts

### Get a single post by ID
GET https://blog-api-service-ehy4.onrender.com/posts/65c81c2049e45e4778590256

### Create a new post
POST https://blog-api-service-ehy4.onrender.com/posts
content-type: application/json
    
{
  "title": "any",
  "author": "any",
  "topics": "any",
  "status": "any",
  "content": "any"
}

### Update a post
PUT https://blog-api-service-ehy4.onrender.com/posts/65c97f13923abcac07b9094a
content-type: application/json
    
{
  //"title": "any",
  //"author": "any",
  //"topics": "any",
  //"status": "any",
  "content": "This post has been edited. That's cool!"
}

### Delete a post
DELETE https://blog-api-service-ehy4.onrender.com/posts/65c97f13923abcac07b9094a
