// LOCALHOST

### Get all posts
GET http://localhost:3000/posts

### Get a single post by ID
GET http://localhost:3000/posts/65d3bd798264c63979a7fa61

### Create a new post
POST http://localhost:3000/posts
content-type: application/json
    
{
  "title": "New Post",
  "author": "Me",
  "topics": ["A Topic", "Another Topic"],
  "status": "Draft",
  "content": "This is another new post."
}

### Update a post
PUT http://localhost:3000/posts/65d05fe013930c39e1da0fa1
content-type: application/json
    
{
  "title": "",
  "author": "",
  "topics": [],
  "status": "",
  "content": ""
}

### Delete a post
DELETE http://localhost:3000/posts/65c97f13923abcac07b9094a

### Get all authors
GET http://localhost:3000/authors

### Get a single author by ID
GET http://localhost:3000/authors/65dabec54bd60276d8065347


// PRODUCTION Deploy

### Get all posts
GET https://blog-api-service-ehy4.onrender.com/posts

### Get a single post by ID
GET https://blog-api-service-ehy4.onrender.com/posts/65c81c2049e45e4778590256

### Create a new post
POST https://blog-api-service-ehy4.onrender.com/posts
content-type: application/json
    
{
  "title": "",
  "author": "",
  "topics": [],
  "status": "",
  "content": ""
}

### Update a post
PUT https://blog-api-service-ehy4.onrender.com/posts/65c97f13923abcac07b9094a
content-type: application/json
    
{
  "title": "",
  "author": "",
  "topics": [],
  "status": "",
  "content": ""
}

### Delete a post
DELETE https://blog-api-service-ehy4.onrender.com/posts/65c97f13923abcac07b9094a

### Get all authors
GET https://blog-api-service-ehy4.onrender.com/authors

### Get a single author by ID
GET https://blog-api-service-ehy4.onrender.com/authors/65dabec54bd60276d8065347